server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/prateek-baheti/micro-service-bank-config
          clone-on-start: true